#!/usr/bin/env -S uv tool run dotdrop install --profile default --cfg
[config]
dotpath = "../"
link_dotfile_default = "relative"
# switch to nolink, below, to install a copy of each file
# link_dotfile_default = "nolink"
link_on_import = "relative"
force_chmod = true

[dotfiles.f_zshrc]
src = "zshrc"
dst = "~/.zshrc"

[dotfiles.f_tmux]
src = "tmux.conf"
dst = "~/.tmux.conf"

[dotfiles.f_ygg]
src = "local/bin/ygg"
dst = "~/.local/bin/ygg"

[dotfiles.f_percollate]
src = "local/bin/percollate"
dst = "~/.local/bin/percollate"

[dotfiles.f_prettier]
src = "local/bin/prettier"
dst = "~/.local/bin/prettier"
link = "nolink"

[dotfiles.f_vinfo]
src = "local/bin/vinfo"
dst = "~/.local/bin/vinfo"

[dotfiles.f_jsonlint]
src = "local/bin/jsonlint"
dst = "~/.local/bin/jsonlint"
link = "nolink"

[dotfiles.f_gtree]
src = "local/bin/gtree"
dst = "~/.local/bin/gtree"

[dotfiles.f_pyright-langserver]
src = "local/bin/pyright-langserver"
dst = "~/.local/bin/pyright-langserver"
link = "nolink"

[dotfiles.f_pdf-information]
src = "local/bin/pdf-information.py"
dst = "~/.local/bin/pdf-information.py"

[dotfiles.f_mvslugify]
src = "local/bin/mvslugify"
dst = "~/.local/bin/mvslugify"

[dotfiles.f_mvh1]
src = "local/bin/mvh1.py"
dst = "~/.local/bin/mvh1"

[dotfiles.f_lfrc]
src = "config/lf/lfrc"
dst = "~/.config/lf/lfrc"

[dotfiles.f_litecli]
src = "config/litecli/config"
dst = "~/.config/litecli/config"

[dotfiles.f_tig]
src = "config/tig/config"
dst = "~/.config/tig/config"

[dotfiles.f_pgcli]
src = "config/pgcli/config"
dst = "~/.config/pgcli/config"

[dotfiles.f_gitatributes]
src = "config/git/attributes"
dst = "~/.config/git/attributes"

[dotfiles.f_gitignore]
src = "config/git/ignore"
dst = "~/.config/git/ignore"

[dotfiles.f_gitconfig]
src = "config/git/config"
dst = "~/.config/git/config"

[dotfiles.f_adf]
src = "local/bin/adf"
dst = "~/.local/bin/adf"

[dotfiles.f_lint-all]
src = "local/bin/lint-all"
dst = "~/.local/bin/lint-all"

[dotfiles.f_config]
src = "config/yamllint/config"
dst = "~/.config/yamllint/config"

[dotfiles.f_renovate_config_validator]
src = "local/bin/renovate-config-validator"
dst = "~/.local/bin/renovate-config-validator"

[dotfiles.f_renovate]
src = "local/bin/renovate"
dst = "~/.local/bin/renovate"

[dotfiles.f_newsboat_urls]
src = "config/newsboat/urls"
dst = "~/.config/newsboat/urls"

[dotfiles.f_newsboat_config]
src = "config/newsboat/config"
dst = "~/.config/newsboat/config"

[dotfiles.f_anslibe_lint]
src = "local/bin/ansible-lint"
dst = "~/.local/bin/ansible-lint"

[dotfiles.f_ghostty]
src = "config/ghostty/config"
dst = "~/.config/ghostty/config"

[profiles.default]
dotfiles = ["ALL"]

# bin/dotdrop.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
