[uv]
url = "https://github.com/astral-sh/uv/releases/download/0.5.11/uv-x86_64-unknown-linux-gnu.tar.gz"
#      https://github.com/astral-sh/uv/releases/download/0.5.11/uv-x86_64-unknown-linux-gnu.tar.gz.sha256
expected = "14411de26cdea5f5139fafaf2b675b1c633e744dd49c6d6a9fc8817ec065158b"
version = "--version"
prefix = "uv-x86_64-unknown-linux-gnu/"
ignore = ["uv-x86_64-unknown-linux-gnu"]

[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.1.1/a4"
# https://github.com/maxwell-k/a4/releases/download/0.1.1/SHA256SUMS
expected = "92cf8ca42095a232ad41274f30e71c258891c3908dd012bf23fec083f18e7ca7"
version = "--version"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.47.6/dprint-x86_64-unknown-linux-gnu.zip"
# https://github.com/dprint/dprint/releases/latest
expected = "cf572c3207ccf870e6f670b1088c843a9b77930e00e8a34239b0dda4a856a237"
version = "--version"

[deno]
# https://github.com/denoland/deno/releases/latest
url = "https://github.com/denoland/deno/releases/download/v2.1.4/deno-x86_64-unknown-linux-gnu.zip"
#      https://github.com/denoland/deno/releases/download/v2.1.4/deno-x86_64-unknown-linux-gnu.zip.sha256sum
expected = "54a81939cccb2af114c4d0a68a554cf4a04b1f08728e70f663f83781de19d785"
target = "~/.deno/bin/deno"
version = "--version"

[git-jump]
url = "https://raw.githubusercontent.com/git/git/master/contrib/git-jump/git-jump"

["osc52.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.sh"

["hterm-notify.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-notify.sh"

["hterm-show-file.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-show-file.sh"

[pip]
# https://pip.pypa.io/en/stable/installation/
url = "https://bootstrap.pypa.io/pip/zipapp/pip-24.3.1.pyz"
version = "--version"
# Python 3.13 is not available on Debian 12 bookworm
command = "python3.11 -m zipapp --python=/usr/bin/python3.11 --output={target} {downloaded}"

[python]
url = "/usr/bin/python3.13"
# Python 3.13 is not available on Debian 12 bookworm
# version = "--version"

[exercism]
url = "https://github.com/exercism/cli/releases/download/v3.5.4/exercism-3.5.4-linux-x86_64.tar.gz"
# https://github.com/exercism/cli/releases/download/v3.5.4/exercism_checksums.txt
expected = "97a18dda052f4766e6b7f1fbfadabf37b32522949516e6416be008c80c068e87"
ignore = [
  "LICENSE",
  "README.md",
  "shell/README.md",
  "shell/exercism.fish",
  "shell/exercism_completion.bash",
  "shell/exercism_completion.zsh",
]
version = "version"

[actionlint]
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.4/actionlint_1.7.4_linux_amd64.tar.gz"
#      https://github.com/rhysd/actionlint/releases/download/v1.7.4/actionlint_1.7.4_checksums.txt
expected = "fc0a6886bbb9a23a39eeec4b176193cadb54ddbe77cdbb19b637933919545395"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
version = "-version"

[fnm]
# <https://github.com/Schniz/fnm/releases>, no checksums provided
url = "https://github.com/Schniz/fnm/releases/download/v1.38.1/fnm-linux.zip"
version = "--version"

[zvm]
# <https://github.com/tristanisham/zvm/releases/>, no checksums provided
url = "https://github.com/tristanisham/zvm/releases/download/v0.8.2/zvm-linux-amd64.tar"
version = "--version"

[dnscontrol]
url = "https://github.com/StackExchange/dnscontrol/releases/download/v4.15.2/dnscontrol_4.15.2_linux_amd64.tar.gz"
#      https://github.com/StackExchange/dnscontrol/releases/download/v4.15.2/checksums.txt
expected = "95371787d3c41cb73895b479bad36d9ef6962ab298751dfa360adfa3539dd1c2"
ignore = ["LICENSE", "README.md"]
version = "version"
