[pipx]
# Manually remove the file from ./downloaded/ on upgrade
url = "https://github.com/pypa/pipx/releases/download/1.6.0/pipx.pyz"
version = "--version"

[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.1.1/a4"
# https://github.com/maxwell-k/a4/releases/download/0.1.1/SHA256SUMS
expected = "92cf8ca42095a232ad41274f30e71c258891c3908dd012bf23fec083f18e7ca7"
version = "--version"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.47.2/dprint-x86_64-unknown-linux-gnu.zip"
# https://github.com/dprint/dprint/releases/latest
expected = "62297402bc9ede9434c33c5de1918d97864002347c0ff85863de7d1ffe6ea384"
version = "--version"

[deno]
# See https://github.com/denoland/deno/issues/7253 for checksum progress
# Manually remove the file from ./downloaded/ on upgrade
url = "https://github.com/denoland/deno/releases/download/v1.45.1/deno-x86_64-unknown-linux-gnu.zip"
# https://github.com/denoland/deno/releases/latest
target = "~/.deno/bin/deno"
version = "--version"

[dyff]
url = "https://github.com/homeport/dyff/releases/download/v1.8.0/dyff_1.8.0_linux_amd64.tar.gz"
# https://github.com/homeport/dyff/releases
expected = "8d487f28177f44ae84a531057c1eded77b8074b0d0591c077e0ec5570b8bc7b7"
version = "version"
completions = "{target} completion zsh"
ignore = ["LICENSE", "README.md"]

[git-jump]
url = "https://raw.githubusercontent.com/git/git/master/contrib/git-jump/git-jump"

["osc52.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.sh"

["hterm-notify.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-notify.sh"

["hterm-show-file.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-show-file.sh"

[pip]
# https://pip.pypa.io/en/stable/installation/, not versioned, latest release
url = "https://bootstrap.pypa.io/pip/pip.pyz"
version = "--version"
command = "python3.11 -m zipapp --python=/usr/bin/python3.11 --output={target} {downloaded}"

[python]
url = "/usr/bin/python3.12"
# Python 3.12 is not available on Debian 12
# version = "--version"

[wp]
# <https://github.com/wp-cli/wp-cli/releases/>, no checksums provided
url = "https://github.com/wp-cli/wp-cli/releases/download/v2.10.0/wp-cli-2.10.0.phar"
version = "--version"

[exercism]
url = "https://github.com/exercism/cli/releases/download/v3.4.0/exercism-3.4.0-linux-x86_64.tar.gz"
# https://github.com/exercism/cli/releases/download/v3.4.0/exercism_checksums.txt
expected = "492b536d7e9ff909beb0e3f866af1b0ace48e5ae76235200c2add67db19a2cf3"
ignore = ["LICENSE", "README.md"]
version = "version"

[actionlint]
# https://github.com/rhysd/actionlint/releases
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.1/actionlint_1.7.1_linux_amd64.tar.gz"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
expected = "f53c34493657dfea83b657e4b62cc68c25fbc383dff64c8d581613b037aacaa3"
version = "-version"

[bump]
# https://github.com/guilhem/bump/releases/download/v0.2.3/checksums.txt
url = "https://github.com/guilhem/bump/releases/download/v0.2.3/bump_Linux_x86_64.tar.gz"
expected = "30f3b862fb7a52183f2177c9ed8808d562d3e04c544ba9b38e97795f9d42950c"
ignore = [
  "LICENSE",
  "README.md",
]
