[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.0.5/a4"
# https://github.com/maxwell-k/a4/releases/download/0.0.5/SHA256SUMS
expected = "1495508aabcfcb979bfcedc86a0f5941463bd743ac076be4ee8a3f13859c02cf"
version = "--version"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.45.0/dprint-x86_64-unknown-linux-gnu.zip"
# https://github.com/dprint/dprint/releases/latest
expected = "581e44d57631498edfed6baad5dd77d832116a12c94dd6fb394045ed40af18ea"
version = "--version"

[deno]
# See https://github.com/denoland/deno/issues/7253 for checksum progress
# Manually remove the file from ./downloaded/ on upgrade
url = "https://github.com/denoland/deno/releases/download/v1.39.1/deno-x86_64-unknown-linux-gnu.zip"
target = "~/.deno/bin/deno"
version = "--version"

[dyff]
url = "https://github.com/homeport/dyff/releases/download/v1.6.0/dyff_1.6.0_linux_amd64.tar.gz"
# https://github.com/homeport/dyff/releases
expected = "d21879c4810f8f97af9ed637b8339a80dfa3fb089bd45cfbeea95b8639b203e1"
version = "version"
completions = true
ignore = ["LICENSE", "README.md"]

[git-jump]
url = "https://raw.githubusercontent.com/git/git/master/contrib/git-jump/git-jump"

["osc52.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.sh"

["hterm-notify.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-notify.sh"

["hterm-show-file.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-show-file.sh"

[pip]
# https://pip.pypa.io/en/stable/installation/, not versioned, latest release
url = "https://bootstrap.pypa.io/pip/pip.pyz"
version = "--version"
command = "python3.11 -m zipapp --python=/usr/bin/python3.11 --output={target} {downloaded}"

[pulumi]
# https://www.pulumi.com/docs/install/
url = "https://get.pulumi.com/releases/sdk/pulumi-v3.99.0-linux-x64.tar.gz"
# https://github.com/pulumi/pulumi/releases/download/v3.99.0/SHA512SUMS
expected = "3d94c42de637574e8b68062fbe34c07ee45cb1072af140f6b9eec288b577df6028d09d4c4bc3f08e6eebba9cbf7c59346aeee6dbbe298b0f1d8f28b3cf6075f4"
prefix = "pulumi/"
version = "version"

[python]
url = "/usr/bin/python3.12"
# Python 3.12 is not available on Debian 12
# version = "--version"

[wp]
# <https://github.com/wp-cli/wp-cli/releases/>, no checksums provided
url = "https://github.com/wp-cli/wp-cli/releases/download/v2.9.0/wp-cli-2.9.0.phar"
version = "--version"

[exercism]
url = "https://github.com/exercism/cli/releases/download/v3.2.0/exercism-3.2.0-linux-x86_64.tar.gz"
# https://github.com/exercism/cli/releases/download/v3.2.0/exercism_checksums.txt
expected = "4ea3e1ea8916a8003da95dbd6eef7a3a29802e637ed6a0f2aaaa2f1c98754915"
ignore = ["LICENSE", "README.md"]
version = "version"
