[uv]
url = "https://github.com/astral-sh/uv/releases/download/0.4.30/uv-x86_64-unknown-linux-gnu.tar.gz"
#      https://github.com/astral-sh/uv/releases/download/0.4.30/uv-x86_64-unknown-linux-gnu.tar.gz.sha256
expected = "5637be5d163ccdcb9f0fe625890d84bbc3596810320be1f56b53bb111edb5dd7"
version = "--version"
prefix = "uv-x86_64-unknown-linux-gnu/"
ignore = ["uv-x86_64-unknown-linux-gnu"]

[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.1.1/a4"
# https://github.com/maxwell-k/a4/releases/download/0.1.1/SHA256SUMS
expected = "92cf8ca42095a232ad41274f30e71c258891c3908dd012bf23fec083f18e7ca7"
version = "--version"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.47.5/dprint-x86_64-unknown-linux-gnu.zip"
# https://github.com/dprint/dprint/releases/latest
expected = "123c20d147485e4cac60823e63c13f2cf9157615e5ffea61b431243f61227343"
version = "--version"

[deno]
# https://github.com/denoland/deno/releases/latest
url = "https://github.com/denoland/deno/releases/download/v2.0.5/deno-x86_64-unknown-linux-gnu.zip"
#      https://github.com/denoland/deno/releases/download/v2.0.5/deno-x86_64-unknown-linux-gnu.zip.sha256sum
expected = "18e1691ff442b8f637325bf29d6729e6f7a8eb9bda3de9916d1a29d01fd5c91b"
target = "~/.deno/bin/deno"
version = "--version"

[git-jump]
url = "https://raw.githubusercontent.com/git/git/master/contrib/git-jump/git-jump"

["osc52.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.sh"

["hterm-notify.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-notify.sh"

["hterm-show-file.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-show-file.sh"

[pip]
# https://pip.pypa.io/en/stable/installation/
url = "https://bootstrap.pypa.io/pip/zipapp/pip-24.3.1.pyz"
version = "--version"
# Python 3.13 is not available on Debian 12 bookworm
command = "python3.11 -m zipapp --python=/usr/bin/python3.11 --output={target} {downloaded}"

[python]
url = "/usr/bin/python3.13"
# Python 3.13 is not available on Debian 12 bookworm
# version = "--version"

[exercism]
url = "https://github.com/exercism/cli/releases/download/v3.5.2/exercism-3.5.2-linux-x86_64.tar.gz"
# https://github.com/exercism/cli/releases/download/v3.5.2/exercism_checksums.txt
expected = "ad7e921b6beea2eda87655b5042650ca6dc6cb7027f3ab6a877b27a2bc14e293"
ignore = [
  "LICENSE",
  "README.md",
  "shell/README.md",
  "shell/exercism.fish",
  "shell/exercism_completion.bash",
  "shell/exercism_completion.zsh",
]
version = "version"

[actionlint]
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.4/actionlint_1.7.4_linux_amd64.tar.gz"
#      https://github.com/rhysd/actionlint/releases/download/v1.7.4/actionlint_1.7.4_checksums.txt
expected = "fc0a6886bbb9a23a39eeec4b176193cadb54ddbe77cdbb19b637933919545395"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
version = "-version"

[fnm]
# <https://github.com/Schniz/fnm/releases>, no checksums provided
url = "https://github.com/Schniz/fnm/releases/download/v1.37.2/fnm-linux.zip"
version = "--version"

[zvm]
# <https://github.com/tristanisham/zvm/releases/>, no checksums provided
url = "https://github.com/tristanisham/zvm/releases/download/v0.7.9/zvm-linux-amd64.tar"
version = "--version"

[dnscontrol]
url = "https://github.com/StackExchange/dnscontrol/releases/download/v4.14.1/dnscontrol_4.14.1_linux_amd64.tar.gz"
#      https://github.com/StackExchange/dnscontrol/releases/download/v4.14.1/checksums.txt
expected = "716d920cfb843aacc8376889ebe2a6679e2129be6061509bf8529d9fd66fe890"
ignore = ["LICENSE", "README.md"]
version = "version"
