[pip]
# https://pip.pypa.io/en/stable/installation/
url = "https://bootstrap.pypa.io/pip/zipapp/pip-25.1.1.pyz"
version = "--version"
# Python 3.13 is not available on Debian 12 bookworm
command = "python3.11 -m zipapp --python=/usr/bin/python3.11 --output={target} {downloaded}"

[python]
url = "/usr/bin/python3.13"
# Python 3.13 is not available on Debian 12 bookworm
# version = "--version"

# bin.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
