[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.0.5/a4"
# https://github.com/maxwell-k/a4/releases/download/0.0.5/SHA256SUMS
expected = "1495508aabcfcb979bfcedc86a0f5941463bd743ac076be4ee8a3f13859c02cf"
version = "--version"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.43.2/dprint-x86_64-unknown-linux-gnu.zip"
target = "~/.local/bin/dprint"
expected = "89a7e33416dfab15c61ac2aad19e82c2bdb3b57f874f9fe3806312a27aa7afd4"
version = "--version"

[deno]
# See https://github.com/denoland/deno/issues/7253 for checksum progress
# Manually remove the file from ./downloaded/ on upgrade
url = "https://github.com/denoland/deno/releases/download/v1.38.4/deno-x86_64-unknown-linux-gnu.zip"
target = "~/.deno/bin/deno"
version = "--version"

[dyff]
url = "https://github.com/homeport/dyff/releases/download/v1.6.0/dyff_1.6.0_linux_amd64.tar.gz"
# https://github.com/homeport/dyff/releases
expected = "d21879c4810f8f97af9ed637b8339a80dfa3fb089bd45cfbeea95b8639b203e1"
target = "~/.local/bin/dyff"
version = "version"
completions = true

[git-jump]
url = "https://raw.githubusercontent.com/git/git/master/contrib/git-jump/git-jump"

["osc52.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.sh"

["hterm-notify.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-notify.sh"

["hterm-show-file.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-show-file.sh"

[pip]
# https://pip.pypa.io/en/stable/installation/, not versioned, latest release
url = "https://bootstrap.pypa.io/pip/pip.pyz"
target = "~/.local/bin/pip"
version = "--version"
command = "python3.11 -m zipapp --python=/usr/bin/python3.11 --output={target} {source}"

[pulumi]
# https://www.pulumi.com/docs/install/
url = "https://get.pulumi.com/releases/sdk/pulumi-v3.95.0-linux-x64.tar.gz"
expected = "5e086e89f04436ae14f802fca5771186390c91156c66e8815577363c7c532aa091176964556198b8d5e50f761d7da13f519c783545747e163813ca120c24a498"
prefix = "pulumi/"
target = "~/.local/bin/pulumi"
version = "version"

[python]
url = "/usr/bin/python3.12"
target = "~/.local/bin/python"
version = "--version"

[wp]
# <https://github.com/wp-cli/wp-cli/releases/>, no checksums provided
url = "https://github.com/wp-cli/wp-cli/releases/download/v2.9.0/wp-cli-2.9.0.phar"
target = "~/.local/bin/wp"
version = "--version"
