[config]
link_on_import = "relative"
dotpath = "dotdrop"

[dotfiles.f_zshrc]
src = "zshrc"
dst = "~/.zshrc"
link = "relative"

[dotfiles.f_deno]
src = "deno/bin/deno"
dst = "~/.deno/bin/deno"
link = "relative"
chmod = "755"

[dotfiles.f_tmux]
src = "tmux.conf"
dst = "~/.tmux.conf"
link = "relative"

[dotfiles.f_ygg]
src = "local/bin/ygg"
dst = "~/.local/bin/ygg"
link = "relative"
chmod = "755"

[dotfiles.f_a4]
src = "local/bin/a4"
dst = "~/.local/bin/a4"
link = "relative"
chmod = "755"

[profiles.default]
dotfiles = ["ALL"]
