[config]
link_on_import = "relative"
dotpath = "dotdrop"

[dotfiles.f_zshrc]
src = "zshrc"
dst = "~/.zshrc"
link = "relative"

[dotfiles.f_deno]
src = "deno/bin/deno"
dst = "~/.deno/bin/deno"
link = "relative"
chmod = "755"

[dotfiles.f_tmux]
src = "tmux.conf"
dst = "~/.tmux.conf"
link = "relative"

[profiles.default]
dotfiles = ["ALL"]
