[config]
link_on_import = "relative"
dotpath = "dotdrop"

[dotfiles.f_zshrc]
src = "zshrc"
dst = "~/.zshrc"
link = "relative"

[dotfiles.f_tmux]
src = "tmux.conf"
dst = "~/.tmux.conf"
link = "relative"

[dotfiles.f_ygg]
src = "local/bin/ygg"
dst = "~/.local/bin/ygg"
link = "relative"
chmod = "755"

[dotfiles.f_percollate]
src = "local/bin/percollate"
dst = "~/.local/bin/percollate"
link = "relative"
chmod = "755"

[dotfiles.f_prettier]
src = "local/bin/prettier"
dst = "~/.local/bin/prettier"
link = "relative"
chmod = "755"

[dotfiles.f_vimj]
src = "local/bin/vimj"
dst = "~/.local/bin/vimj"
link = "relative"
chmod = "755"

[profiles.default]
dotfiles = ["ALL"]
