[config]
link_dotfile_default = "relative"
link_on_import = "relative"
dotpath = "dotdrop"

[dotfiles.f_zshrc]
src = "zshrc"
dst = "~/.zshrc"

[dotfiles.f_tmux]
src = "tmux.conf"
dst = "~/.tmux.conf"

[dotfiles.f_ygg]
src = "local/bin/ygg"
dst = "~/.local/bin/ygg"
chmod = "755"

[dotfiles.f_percollate]
src = "local/bin/percollate"
dst = "~/.local/bin/percollate"
chmod = "755"

[dotfiles.f_prettier]
src = "local/bin/prettier"
dst = "~/.local/bin/prettier"
chmod = "755"

[dotfiles.f_vimj]
src = "local/bin/vimj"
dst = "~/.local/bin/vimj"
chmod = "755"

[dotfiles.f_vinfo]
src = "local/bin/vinfo"
dst = "~/.local/bin/vinfo"
chmod = "755"

[dotfiles.f_jsonlint]
src = "local/bin/jsonlint"
dst = "~/.local/bin/jsonlint"
chmod = "755"

[dotfiles.f_title]
src = "local/bin/title"
dst = "~/.local/bin/title"
chmod = "755"

[dotfiles.f_pager]
src = "local/bin/pager"
dst = "~/.local/bin/pager"
chmod = "755"

[dotfiles.f_gtree]
src = "local/bin/gtree"
dst = "~/.local/bin/gtree"
chmod = "755"

[dotfiles.f_pyright-langserver]
src = "local/bin/pyright-langserver"
dst = "~/.local/bin/pyright-langserver"
chmod = "755"

[dotfiles.f_pdf-information]
src = "local/bin/pdf-information.py"
dst = "~/.local/bin/pdf-information.py"
chmod = "755"

[dotfiles.f_tasks]
src = "local/bin/tasks"
dst = "~/.local/bin/tasks"
chmod = "755"

[dotfiles.f_flake8]
src = "config/flake8"
dst = "~/.config/flake8"

[dotfiles.f_lfrc]
src = "config/lf/lfrc"
dst = "~/.config/lf/lfrc"

[profiles.default]
dotfiles = ["ALL"]
