#!/usr/bin/env -S uv tool run dotlocalslashbin --input
[git-jump]
url = "https://raw.githubusercontent.com/git/git/master/contrib/git-jump/git-jump"

["osc52.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/osc52.sh"

["hterm-notify.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-notify.sh"

["hterm-show-file.sh"]
url = "https://raw.githubusercontent.com/libapps/libapps-mirror/master/hterm/etc/hterm-show-file.sh"

# github.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
