[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.1.1/a4"
# https://github.com/maxwell-k/a4/releases/download/0.1.1/SHA256SUMS
expected = "92cf8ca42095a232ad41274f30e71c258891c3908dd012bf23fec083f18e7ca7"
version = "--version"

[actionlint]
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz"
#      https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_checksums.txt
expected = "023070a287cd8cccd71515fedc843f1985bf96c436b7effaecce67290e7e0757"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
version = "-version"

[deno]
# https://github.com/denoland/deno/releases/latest
url = "https://github.com/denoland/deno/releases/download/v2.3.3/deno-x86_64-unknown-linux-gnu.zip"
expected = "cb573ef18e06b6f17db31b7a410143abfebe0c8d1faa99cb934a7c1351c75701" # update with: ./helpers/deno.py
target = "~/.deno/bin/deno"
version = "--version"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.50.0/dprint-x86_64-unknown-linux-gnu.zip"
#      https://github.com/dprint/dprint/releases/download/0.50.0/SHASUMS256.txt
expected = "06c9eb656c8021f03e75620d391304de29ad540ee714bd23f91243370ac4435c"
version = "--version"

[uv]
url = "https://github.com/astral-sh/uv/releases/download/0.7.5/uv-x86_64-unknown-linux-gnu.tar.gz"
expected = "a3d1964080a855e1f8806975b5fa943376045a64852c06ba80540813aa333305" # update with: ./helpers/uv.py
version = "--version"
prefix = "uv-x86_64-unknown-linux-gnu/"
ignore = ["uv-x86_64-unknown-linux-gnu"]

# linux-amd64.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
