#!/usr/bin/env -S uv tool run dotlocalslashbin --input
[a4]
url = "https://github.com/maxwell-k/a4/releases/download/0.2.0/a4"
expected = "a15420c22fd67b2a31e54467c63a0dec8e060ee59b5005d9a66896c207672591" # ./update.py a4
version = "--version"
modifier = "SHA256SUMS"

[actionlint]
url = "https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz"
#      https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_checksums.txt
expected = "023070a287cd8cccd71515fedc843f1985bf96c436b7effaecce67290e7e0757"
ignore = [
  "LICENSE.txt",
  "README.md",
  "docs/README.md",
  "docs/api.md",
  "docs/checks.md",
  "docs/config.md",
  "docs/install.md",
  "docs/reference.md",
  "docs/usage.md",
  "man/actionlint.1",
]
version = "-version"

[deno]
url = "https://github.com/denoland/deno/releases/download/v2.4.1/deno-x86_64-unknown-linux-gnu.zip"
expected = "9cd61b07ddd4956aa1ca5b4a0d7f3a404da8e5fd6228d22e1a6486aafcc081a9" # ./update.py deno
target = "~/.deno/bin/deno"
version = "--version"
modifier = ".sha256sum"

[dprint]
url = "https://github.com/dprint/dprint/releases/download/0.50.1/dprint-x86_64-unknown-linux-gnu.zip"
expected = "11d791a5da5178a6d1359f23ea00b2d47426672fe310c5f32da2c66e80e07675" # ./update.py dprint
version = "--version"
modifier = "SHASUMS256.txt"

[uv]
url = "https://github.com/astral-sh/uv/releases/download/0.7.20/uv-x86_64-unknown-linux-gnu.tar.gz"
expected = "10f204426ff188925d22a53c1d0310d190a8d4d24513712e1b8e2ca9873f0666" # ./update.py uv
version = "--version"
prefix = "uv-x86_64-unknown-linux-gnu/"
ignore = ["uv-x86_64-unknown-linux-gnu"]
modifier = ".sha256"

# linux-amd64.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
