version = 1
SPDX-PackageName = "dotfiles"
SPDX-PackageSupplier = "Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/maxwell-k/dotfiles"

[[annotations]]
path = [
  # file formats that do no suit comments
  ".en.utf-8.add",
  ".gitignore",
  "dotfiles/config/git/attributes",
  "dotfiles/config/git/ignore",
  "dprint.json",
]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  # includied in README.md so hide comments here
  ".README.md-files/**.sh",
  # files are two lines each, so avoid three extra lines of comments
  "dotfiles/local/bin/gtree",
  "dotfiles/local/bin/jsonlint",
  "dotfiles/local/bin/percollate",
  "dotfiles/local/bin/prettier",
  "dotfiles/local/bin/pyright-langserver",
  "dotfiles/local/bin/title",
  "dotfiles/local/bin/vimf",
  "dotfiles/local/bin/vimj",
  "dotfiles/local/bin/vinfo",
]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "MPL-2.0"

# REUSE.toml
# SPDX-FileCopyrightText: 2025 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
