version = 1
SPDX-PackageName = "dotfiles"
SPDX-PackageSupplier = "Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/maxwell-k/dotfiles"

[[annotations]]
path = [
  ".en.utf-8.add",
  ".flake8",
  ".gitignore",
  "README.md",
  "bin.toml",
  "config.toml",
  "dotfiles/config/flake8",
  "dotfiles/config/git/attributes",
  "dotfiles/config/git/config",
  "dotfiles/config/git/ignore",
  "dotfiles/config/lf/lfrc",
  "dotfiles/config/litecli/config",
  "dotfiles/config/pgcli/config",
  "dotfiles/config/yamllint/config",
  "dprint.json",
]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  ".README.md-files/**.sh",
  "dotfiles/local/bin/gtree",
  "dotfiles/local/bin/jsonlint",
  "dotfiles/local/bin/percollate",
  "dotfiles/local/bin/prettier",
  "dotfiles/local/bin/pyright-langserver",
  "dotfiles/local/bin/title",
  "dotfiles/local/bin/vimf",
  "dotfiles/local/bin/vimj",
  "dotfiles/local/bin/vinfo",
]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "MPL-2.0"

# SPDX-FileCopyrightText: 2025 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
