version = 1
SPDX-PackageName = "dotfiles"
SPDX-PackageSupplier = "Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/maxwell-k/dotfiles"

[[annotations]]
path = [
  # file formats that do no suit comments
  ".en.utf-8.add",
  ".gitignore",
  "config/git/attributes",
  "config/git/ignore",
  ".dprint.json",
]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  # also included in ~/.vim/site.yaml
  "local/bin/jsonlint",
  "local/bin/prettier",
  "local/bin/pyright-langserver",
  # includied in README.md so hide comments here
  ".README.md-files/01.sh",
  ".README.md-files/03.sh",
  ".README.md-files/02.sh",
  ".README.md-files/04.sh",
]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "MPL-2.0"

# REUSE.toml
# SPDX-FileCopyrightText: 2025 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
