# .github/workflows/bin-on-incus.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - ./tests/setup-fedora.sh
          - ./tests/setup-debian.sh
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/reset-network.sh
      - run: ./.github/install-incus.sh
      - run: ${{ matrix.script }}
      - run: ./tests/bin-on-incus.sh
        env: { LOGNAME: maxwell-k }
