# .github/workflows/bin-on-fedora.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: canonical/setup-lxd@v0.1.1
      - run: ./.github/profile.sh
      - run: ./tests/bin-on-fedora.sh
        env: { LOGNAME: maxwell-k }
