# .github/workflows/matrix.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - MATRIX_IMAGE: "" # use defaults in ./tests/matrix.sh
          - MATRIX_IMAGE: debian/13/cloud
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: maxwell-k/setup-incus@main
      - run: incus admin init --auto
      - run: ./tests/matrix.sh
        env:
          LOGNAME: maxwell-k
          MATRIX_IMAGE: ${{ matrix.MATRIX_IMAGE }}
