# .github/workflows/bin-on-incus.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - SETUP_IMAGE: "" # use defaults in ./tests/setup.sh
            SETUP_CONFIG: ""
          - SETUP_IMAGE: debian/12/cloud
            SETUP_CONFIG: tests/config-debian.yaml
    steps:
      - uses: actions/checkout@v4
      - uses: maxwell-k/setup-incus@main
      - run: incus admin init --auto
      - run: ./tests/setup.sh
        env:
          LOGNAME: maxwell-k
          SETUP_CONFIG: ${{ matrix.SETUP_CONFIG }}
          SETUP_IMAGE: ${{ matrix.SETUP_IMAGE }}
