# .github/workflows/readme.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: canonical/setup-lxd@v0.1.1
      - run: ./.github/profile.sh
      - run: ./.README.md-files/00.sh
      - run: ./.README.md-files/02.sh
        env:
          HOME: /home/maxwell-k
          LOGNAME: maxwell-k
      - run: ./.README.md-files/cleanup.sh
