# .github/workflows/readme.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/reset-network.sh
      - run: ./.github/install-incus.sh
      - run: incus profile edit default < .github/incus-profile.yaml
      - { run: ./.README.md-files/01.sh, env: { LOGNAME: maxwell-k } }
      - { run: ./.README.md-files/03.sh, env: { LOGNAME: maxwell-k } }
      - run: incus exec c1 -- su --login maxwell-k < .README.md-files/02.sh
      - run: incus exec c1 -- su --login maxwell-k < .README.md-files/04.sh
      - run: ./.README.md-files/cleanup.sh
